# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-10 05:14
from __future__ import unicode_literals

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('phone_1', models.CharField(max_length=30)),
                ('phone_2', models.CharField(blank=True, max_length=30, null=True)),
                ('gid', models.IntegerField(blank=True, null=True)),
                ('gname', models.CharField(blank=True, max_length=80, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('bid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AcademySchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.IntegerField()),
                ('aid', models.CharField(blank=True, max_length=20, null=True)),
                ('aname', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), size=None)),
                ('schedule1', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), size=None)),
                ('schedule2', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), size=None)),
                ('schedule3', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), size=None)),
                ('schedule4', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), size=None)),
                ('schedule5', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), size=None)),
                ('schedule6', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('a_name', models.CharField(max_length=50)),
                ('schedule', models.CharField(max_length=50)),
                ('absence', models.IntegerField()),
                ('d_date', models.DateField()),
                ('student_id', models.IntegerField()),
                ('academy_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(default='', max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('lon', models.FloatField(default=0, null=True)),
                ('lat', models.FloatField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aname', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField(default=datetime.date.today)),
                ('complain', models.TextField()),
                ('plan', models.TextField()),
                ('showdate', models.CharField(max_length=50)),
                ('clike', models.IntegerField(default=0)),
                ('dlike', models.IntegerField(default=0)),
                ('disuserid', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0, null=True), size=None)),
                ('likeuserid', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0, null=True), size=None)),
                ('disuser', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=30, null=True), size=None)),
                ('likeuser', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=30, null=True), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shuttle_id', models.IntegerField()),
                ('driver_id', models.IntegerField()),
                ('passenger_id', models.IntegerField()),
                ('academy_id', models.IntegerField()),
                ('driver_rating', models.IntegerField()),
                ('driver_velocity_rating', models.IntegerField()),
                ('passenger_rating', models.IntegerField()),
                ('before_1', models.IntegerField()),
                ('before_2', models.IntegerField(blank=True, null=True)),
                ('before_3', models.IntegerField(blank=True, null=True)),
                ('before_4', models.IntegerField(blank=True, null=True)),
                ('after_1', models.IntegerField()),
                ('after_2', models.IntegerField(blank=True, null=True)),
                ('after_3', models.IntegerField(blank=True, null=True)),
                ('after_4', models.IntegerField(blank=True, null=True)),
                ('total_load', models.IntegerField()),
                ('load_num', models.IntegerField()),
                ('total_unload', models.IntegerField()),
                ('unload_num', models.IntegerField()),
                ('unload_stu', models.CharField(max_length=100)),
                ('good_stu', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(blank=True, max_length=80, null=True)),
                ('academies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30, null=True), size=None)),
                ('gid', models.IntegerField(blank=True, null=True)),
                ('bid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PhoneList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('aid', models.IntegerField(choices=[(15, 'GSE'), (7, '\uc5d0\ub69c\uc54c'), (13, '\uc720\ub2c8\uc544\ud2b8\ubbf8\uc220'), (12, '\ubca0\ubca0\uad81'), (10, '\ub7a8\ube0c\ub780\ud2b8'), (6, '\uc0dd\uac01\uc758\ube5b'), (5, '\uc815\uc9c0\ud6c8\ub17c\uc220\ud559\uc6d0'), (17, '\uc6d0\ud615\ubbf8\uc220'), (31, 'UNSW'), (21, '\uc774\ud654\ubc1c\ub808'), (24, '\uba54\uac00\uc218\ud559'), (23, '\ud574\ubc95\uc218\ud559'), (22, '\ud574\ubc95\uc601\uc5b4'), (3, '\ud504\ub9ac\ubaa8\uc74c\uc545\ud559\uc6d0'), (32, '\uc6b0\ub9ac\uc544\uc774'), (30, '\ub9c8\ub8e8\uc9c0'), (27, '\ud0a4\uc2a4\ud1a4'), (28, '\uc720\ub2c8\ucf58'), (29, '\uc81c\ub2c8\uc2a4'), (26, '\ud5ec\ub85c\uc544\ud2b8'), (25, '\uc608\uc18c\uc2a4'), (34, '\ubbf8\uc0ac\ub9c8\ub8e8\uc9c0')])),
                ('aname', models.CharField(choices=[('GSE', 'GSE'), ('\uc5d0\ub69c\uc54c', '\uc5d0\ub69c\uc54c'), ('\uc720\ub2c8\uc544\ud2b8\ubbf8\uc220', '\uc720\ub2c8\uc544\ud2b8\ubbf8\uc220'), ('\ubca0\ubca0\uad81', '\ubca0\ubca0\uad81'), ('\ub7a8\ube0c\ub780\ud2b8', '\ub7a8\ube0c\ub780\ud2b8'), ('\uc0dd\uac01\uc758\ube5b', '\uc0dd\uac01\uc758\ube5b'), ('\uc815\uc9c0\ud6c8\ub17c\uc220\ud559\uc6d0', '\uc815\uc9c0\ud6c8\ub17c\uc220\ud559\uc6d0'), ('\uc6d0\ud615\ubbf8\uc220', '\uc6d0\ud615\ubbf8\uc220'), ('UNSW', 'UNSW'), ('\uc774\ud654\ubc1c\ub808', '\uc774\ud654\ubc1c\ub808'), ('\uba54\uac00\uc218\ud559', '\uba54\uac00\uc218\ud559'), ('\ud574\ubc95\uc218\ud559', '\ud574\ubc95\uc218\ud559'), ('\ud574\ubc95\uc601\uc5b4', '\ud574\ubc95\uc601\uc5b4'), ('\ud504\ub9ac\ubaa8\uc74c\uc545\ud559\uc6d0', '\ud504\ub9ac\ubaa8\uc74c\uc545\ud559\uc6d0'), ('\uc6b0\ub9ac\uc544\uc774', '\uc6b0\ub9ac\uc544\uc774'), ('\ub9c8\ub8e8\uc9c0', '\ub9c8\ub8e8\uc9c0'), ('\ud0a4\uc2a4\ud1a4', '\ud0a4\uc2a4\ud1a4'), ('\uc720\ub2c8\ucf58', '\uc720\ub2c8\ucf58'), ('\uc81c\ub2c8\uc2a4', '\uc81c\ub2c8\uc2a4'), ('\ud5ec\ub85c\uc544\ud2b8', '\ud5ec\ub85c\uc544\ud2b8'), ('\uc608\uc18c\uc2a4', '\uc608\uc18c\uc2a4'), ('\ubbf8\uc0ac\ub9c8\ub8e8\uc9c0', '\ubbf8\uc0ac\ub9c8\ub8e8\uc9c0')], max_length=30)),
                ('phone1', models.CharField(blank=True, max_length=30, null=True)),
                ('phone2', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('s_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('s_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('m_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('f_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('schedule', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30, null=True), size=None)),
                ('load', models.CharField(blank=True, max_length=10, null=True)),
                ('unload', models.CharField(blank=True, max_length=10, null=True)),
                ('academy_id', models.IntegerField(blank=True, null=True)),
                ('gid', models.IntegerField(blank=True, null=True)),
                ('l_lon', models.FloatField(blank=True, null=True)),
                ('l_lat', models.FloatField(blank=True, null=True)),
                ('u_lon', models.FloatField(blank=True, null=True)),
                ('u_lat', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(max_length=30)),
                ('day', models.CharField(max_length=10)),
                ('time', models.IntegerField()),
                ('schedule', models.TextField()),
                ('gid', models.IntegerField()),
                ('aid', models.IntegerField()),
                ('slist', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, default=0, null=True), size=None)),
                ('p_schedule', models.TextField(blank=True, null=True)),
                ('alist', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, default=0, null=True), size=None)),
                ('memo', models.TextField(blank=True, null=True)),
                ('date', models.CharField(max_length=30)),
                ('today', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Shuttle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('car_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ShuttleSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(max_length=30)),
                ('day', models.CharField(max_length=10)),
                ('time', models.IntegerField()),
                ('schedule', models.TextField()),
                ('gid', models.IntegerField(choices=[(1, '1\ud638\ucc28'), (3, '2\ud638\ucc28'), (5, '3\ud638\ucc28'), (4, '4\ud638\ucc28'), (2, '5\ud638\ucc28'), (6, '6\ud638\ucc28'), (7, '7\ud638\ucc28'), (8, '8\ud638\ucc28')])),
                ('aid', models.IntegerField(choices=[(15, 'GSE'), (7, '\uc5d0\ub69c\uc54c'), (13, '\uc720\ub2c8\uc544\ud2b8\ubbf8\uc220'), (12, '\ubca0\ubca0\uad81'), (10, '\ub7a8\ube0c\ub780\ud2b8'), (6, '\uc0dd\uac01\uc758\ube5b'), (5, '\uc815\uc9c0\ud6c8\ub17c\uc220\ud559\uc6d0'), (17, '\uc6d0\ud615\ubbf8\uc220'), (31, 'UNSW'), (21, '\uc774\ud654\ubc1c\ub808'), (24, '\uba54\uac00\uc218\ud559'), (23, '\ud574\ubc95\uc218\ud559'), (22, '\ud574\ubc95\uc601\uc5b4'), (3, '\ud504\ub9ac\ubaa8\uc74c\uc545\ud559\uc6d0'), (32, '\uc6b0\ub9ac\uc544\uc774'), (30, '\ub9c8\ub8e8\uc9c0'), (27, '\ud0a4\uc2a4\ud1a4'), (28, '\uc720\ub2c8\ucf58'), (29, '\uc81c\ub2c8\uc2a4'), (26, '\ud5ec\ub85c\uc544\ud2b8'), (25, '\uc608\uc18c\uc2a4'), (34, '\ubbf8\uc0ac\ub9c8\ub8e8\uc9c0')])),
                ('slist', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, default=0, null=True), size=None)),
                ('p_schedule', models.TextField(blank=True, null=True)),
                ('alist', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, default=0, null=True), size=None)),
                ('memo', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('a_name', models.CharField(max_length=50)),
                ('day', models.CharField(max_length=20)),
                ('stime', models.IntegerField(blank=True, null=True)),
                ('etime', models.IntegerField(blank=True, null=True)),
                ('aid', models.IntegerField()),
                ('onlocation', models.CharField(blank=True, max_length=50, null=True)),
                ('offlocation', models.CharField(blank=True, max_length=50, null=True)),
                ('on_lon', models.FloatField(blank=True, default=0, null=True)),
                ('on_lat', models.FloatField(blank=True, default=0, null=True)),
                ('off_lon', models.FloatField(blank=True, default=0, null=True)),
                ('off_lat', models.FloatField(blank=True, default=0, null=True)),
                ('etc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.IntegerField()),
                ('bid', models.IntegerField()),
                ('aname', models.CharField(max_length=20)),
                ('sname', models.CharField(max_length=10)),
                ('bname', models.CharField(max_length=20)),
                ('phone1', models.IntegerField()),
                ('phone2', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
