# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-13 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='bid',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='phonelist',
            name='aid',
            field=models.IntegerField(choices=[(15, 'GSE'), (7, '\uc5d0\ub69c\uc54c'), (13, '\uc720\ub2c8\uc544\ud2b8\ubbf8\uc220'), (12, '\ubca0\ubca0\uad81'), (10, '\ub7a8\ube0c\ub780\ud2b8'), (6, '\uc0dd\uac01\uc758\ube5b'), (5, '\uc815\uc9c0\ud6c8\ub17c\uc220\ud559\uc6d0'), (17, '\uc6d0\ud615\ubbf8\uc220'), (31, 'UNSW'), (32, '\uc6b0\ub9ac\uc544\uc774'), (21, '\uc774\ud654\ubc1c\ub808'), (24, '\uba54\uac00\uc218\ud559'), (23, '\ud574\ubc95\uc218\ud559'), (22, '\ud574\ubc95\uc601\uc5b4'), (3, '\ud504\ub9ac\ubaa8\uc74c\uc545\ud559\uc6d0'), (30, '\ub9c8\ub8e8\uc9c0'), (27, '\ud0a4\uc2a4\ud1a4'), (28, '\uc720\ub2c8\ucf58'), (29, '\uc81c\ub2c8\uc2a4'), (26, '\ud5ec\ub85c\uc544\ud2b8'), (25, '\uc608\uc18c\uc2a4'), (34, '\ubbf8\uc0ac\ub9c8\ub8e8\uc9c0')]),
        ),
        migrations.AlterField(
            model_name='phonelist',
            name='aname',
            field=models.CharField(choices=[('GSE', 'GSE'), ('\uc5d0\ub69c\uc54c', '\uc5d0\ub69c\uc54c'), ('\uc720\ub2c8\uc544\ud2b8\ubbf8\uc220', '\uc720\ub2c8\uc544\ud2b8\ubbf8\uc220'), ('\ubca0\ubca0\uad81', '\ubca0\ubca0\uad81'), ('\ub7a8\ube0c\ub780\ud2b8', '\ub7a8\ube0c\ub780\ud2b8'), ('\uc0dd\uac01\uc758\ube5b', '\uc0dd\uac01\uc758\ube5b'), ('\uc815\uc9c0\ud6c8\ub17c\uc220\ud559\uc6d0', '\uc815\uc9c0\ud6c8\ub17c\uc220\ud559\uc6d0'), ('\uc6d0\ud615\ubbf8\uc220', '\uc6d0\ud615\ubbf8\uc220'), ('UNSW', 'UNSW'), ('\uc6b0\ub9ac\uc544\uc774', '\uc6b0\ub9ac\uc544\uc774'), ('\uc774\ud654\ubc1c\ub808', '\uc774\ud654\ubc1c\ub808'), ('\uba54\uac00\uc218\ud559', '\uba54\uac00\uc218\ud559'), ('\ud574\ubc95\uc218\ud559', '\ud574\ubc95\uc218\ud559'), ('\ud574\ubc95\uc601\uc5b4', '\ud574\ubc95\uc601\uc5b4'), ('\ud504\ub9ac\ubaa8\uc74c\uc545\ud559\uc6d0', '\ud504\ub9ac\ubaa8\uc74c\uc545\ud559\uc6d0'), ('\ub9c8\ub8e8\uc9c0', '\ub9c8\ub8e8\uc9c0'), ('\ud0a4\uc2a4\ud1a4', '\ud0a4\uc2a4\ud1a4'), ('\uc720\ub2c8\ucf58', '\uc720\ub2c8\ucf58'), ('\uc81c\ub2c8\uc2a4', '\uc81c\ub2c8\uc2a4'), ('\ud5ec\ub85c\uc544\ud2b8', '\ud5ec\ub85c\uc544\ud2b8'), ('\uc608\uc18c\uc2a4', '\uc608\uc18c\uc2a4'), ('\ubbf8\uc0ac\ub9c8\ub8e8\uc9c0', '\ubbf8\uc0ac\ub9c8\ub8e8\uc9c0')], max_length=30),
        ),
        migrations.AlterField(
            model_name='shuttleschedule',
            name='aid',
            field=models.IntegerField(choices=[(15, 'GSE'), (7, '\uc5d0\ub69c\uc54c'), (13, '\uc720\ub2c8\uc544\ud2b8\ubbf8\uc220'), (12, '\ubca0\ubca0\uad81'), (10, '\ub7a8\ube0c\ub780\ud2b8'), (6, '\uc0dd\uac01\uc758\ube5b'), (5, '\uc815\uc9c0\ud6c8\ub17c\uc220\ud559\uc6d0'), (17, '\uc6d0\ud615\ubbf8\uc220'), (31, 'UNSW'), (32, '\uc6b0\ub9ac\uc544\uc774'), (21, '\uc774\ud654\ubc1c\ub808'), (24, '\uba54\uac00\uc218\ud559'), (23, '\ud574\ubc95\uc218\ud559'), (22, '\ud574\ubc95\uc601\uc5b4'), (3, '\ud504\ub9ac\ubaa8\uc74c\uc545\ud559\uc6d0'), (30, '\ub9c8\ub8e8\uc9c0'), (27, '\ud0a4\uc2a4\ud1a4'), (28, '\uc720\ub2c8\ucf58'), (29, '\uc81c\ub2c8\uc2a4'), (26, '\ud5ec\ub85c\uc544\ud2b8'), (25, '\uc608\uc18c\uc2a4'), (34, '\ubbf8\uc0ac\ub9c8\ub8e8\uc9c0')]),
        ),
    ]
