# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-13 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0002_auto_20170413_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='shuttleschedule',
            name='bid',
            field=models.IntegerField(blank=1, null=True),
        ),
    ]
