# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-27 14:42
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=15)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('carlist', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('alist', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carnum', models.IntegerField()),
                ('bid', models.IntegerField()),
                ('snum', models.IntegerField()),
                ('day', models.CharField(max_length=5)),
                ('alist', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('anamelist', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=set(['none']), max_length=10), default=set(['none']), size=None)),
                ('slist', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('stime', models.IntegerField()),
                ('etime', models.IntegerField()),
            ],
            options={
                'ordering': ['stime'],
            },
        ),
        migrations.CreateModel(
            name='InventoryRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iid', models.IntegerField()),
                ('aid', models.IntegerField()),
                ('aname', models.CharField(max_length=10)),
                ('sid', models.IntegerField()),
                ('sname', models.CharField(max_length=10)),
                ('kind', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('contents', models.TextField()),
                ('done', models.IntegerField()),
                ('towho', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(blank=True, max_length=10, null=True)),
                ('addr', models.CharField(blank=True, max_length=30, null=True)),
                ('alist', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None)),
                ('anamelist', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10, null=True), blank=True, null=True, size=None)),
                ('slist', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None)),
                ('sname', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10, null=True), blank=True, null=True, size=None)),
                ('tflag', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None)),
                ('lflag', models.IntegerField()),
                ('iid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduletables', to='schedule.Inventory')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
