# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-28 01:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryrequest',
            name='iid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventoryrequest', to='schedule.Inventory'),
        ),
    ]
